version: 0.2
phases:
  install:
    runtime-versions:
      golang: 1.12
  build:
    commands:
      - "echo resolved source version: $CODEBUILD_RESOLVED_SOURCE_VERSION"
      - "echo source version: $CODEBUILD_SOURCE_VERSION"
      - make docker-push VERSION=$CODEBUILD_RESOLVED_SOURCE_VERSION
artifacts:
  files: []